const MAX_RECALL_BYTES_DEFAULT = 4096;
const MAX_CONTENT_CHARS = 2e3;
const MAX_TAGS = 10;
const MAX_QUERY_CHARS = 500;
const DEFAULT_LIMIT = 10;
const MAX_LIMIT = 50;
export {
  DEFAULT_LIMIT,
  MAX_CONTENT_CHARS,
  MAX_LIMIT,
  MAX_QUERY_CHARS,
  MAX_RECALL_BYTES_DEFAULT,
  MAX_TAGS
};
//# sourceMappingURL=constants.js.map
